spring.application.name=app

#need to enable the h2 console to view the in-memory database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:mem:testdb

# JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


